### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by CheccoFire** [theuhdirector/RPH-Assassin-Mod#1]
**Describe the bug**
The plugin crashes as soon as it is started from RPH.

**Screenshots**
![image](https://user-images.githubusercontent.com/30508161/102709320-c8c21180-42a9-11eb-9581-1b4ed7dcfe8a.png)

**Comment by theuhdirector** [comment]
This plugin is super old and I don't really remember anything about it. Sorry about that. I'm going to archive this repo now.
